######################################
# Makefile by CubeMX2Makefile.py
######################################

######################################
# target
######################################
TARGET = gps_test

######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Ofast

#######################################
# pathes
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
C_SOURCES = \
  app/app_main.c \
  Controls/controls_595.c \
  dev/compass.c \
  dev/gps.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c \
  gui/gui.c \
  gui/gui_compass.c \
  gui/inputs.c \
  MakiseGUI/MakiseGUI/makise.c \
  MakiseGUI/MakiseGUI/makise_colors.c \
  MakiseGUI/MakiseGUI/makise_primitives.c \
  MakiseGUI/MakiseGUI/makise_text.c \
  MakiseGUI/MakiseGUI/fonts/Arial12.c \
  MakiseGUI/MakiseGUI/fonts/Arial15.c \
  MakiseGUI/MakiseGUI/fonts/Arial16.c \
  MakiseGUI/MakiseGUI/fonts/Arial24.c \
  MakiseGUI/MakiseGUI/fonts/fonts.c \
  MakiseGUI/MakiseGUI/gui/makise_gui.c \
  MakiseGUI/MakiseGUI/gui/makise_gui_container.c \
  MakiseGUI/MakiseGUI/gui/makise_gui_elements.c \
  MakiseGUI/MakiseGUI/gui/makise_gui_input.c \
  MakiseGUI/MakiseGUI/gui/elements/makise_e.c \
  MakiseGUI/MakiseGUI/gui/elements/makise_e_buttons.c \
  MakiseGUI/MakiseGUI/gui/elements/makise_e_canvas.c \
  MakiseGUI/MakiseGUI/gui/elements/makise_e_lable.c \
  MakiseGUI/MakiseGUI/gui/elements/makise_e_slider.c \
  MakiseGUI/MakiseGUI/gui/elements/makise_e_slist.c \
  MakiseGUI/MakiseGUI/gui/elements/makise_e_tabs.c \
  MakiseGUI/MakiseGUI/gui/elements/makise_e_text_field.c \
  MakiseGUI/MakiseGUI/ILI9340C/ili9340.c \
  Middlewares/Third_Party/FatFs/src/diskio.c \
  Middlewares/Third_Party/FatFs/src/ff.c \
  Middlewares/Third_Party/FatFs/src/ff_gen_drv.c \
  Middlewares/Third_Party/FatFs/src/drivers/sd_diskio.c \
  Middlewares/Third_Party/FatFs/src/option/syscall.c \
  Src/bsp_driver_sd.c \
  Src/dma.c \
  Src/fatfs.c \
  Src/gpio.c \
  Src/i2c.c \
  Src/main.c \
  Src/printf.c \
  Src/sdio.c \
  Src/spi.c \
  Src/stm32f4xx_hal_msp.c \
  Src/stm32f4xx_it.c \
  Src/system_stm32f4xx.c \
  Src/tim.c \
  Src/usart.c  
ASM_SOURCES = \
  Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/startup_stm32f401xe.s

#######################################
# binaries
#######################################
CC = arm-none-eabi-gcc
AS = arm-none-eabi-gcc -x assembler-with-cpp
CP = arm-none-eabi-objcopy
AR = arm-none-eabi-ar
SZ = arm-none-eabi-size
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# macros for gcc
AS_DEFS =
C_DEFS = -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F401xE
# includes for gcc
AS_INCLUDES =
C_INCLUDES = -Iapp
C_INCLUDES += -IControls
C_INCLUDES += -Idev
C_INCLUDES += -IDrivers/CMSIS/Device/ST/STM32F4xx/Include
C_INCLUDES += -IDrivers/CMSIS/Include
C_INCLUDES += -IDrivers/STM32F4xx_HAL_Driver/Inc
C_INCLUDES += -IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy
C_INCLUDES += -Igui
C_INCLUDES += -IInc
C_INCLUDES += -IMakiseGUI/MakiseGUI
C_INCLUDES += -IMakiseGUI/MakiseGUI/fonts
C_INCLUDES += -IMakiseGUI/MakiseGUI/gui
C_INCLUDES += -IMakiseGUI/MakiseGUI/gui/elements
C_INCLUDES += -IMakiseGUI/MakiseGUI/gui/styles
C_INCLUDES += -IMakiseGUI/MakiseGUI/ILI9340C
C_INCLUDES += -IMiddlewares/Third_Party/FatFs/src
C_INCLUDES += -IMiddlewares/Third_Party/FatFs/src/drivers
# compile gcc flags
ASFLAGS = -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections
CFLAGS = -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections
ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif
# Generate dependency information
CFLAGS += -std=c99 -MD -MP -MF .dep/$(@F).d

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F401RETx_FLASH.ld
# libraries
LIBS = -lc -lm -lnosys
LIBDIR =
LDFLAGS = -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections -u _printf_float

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin

#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir -p $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR .dep $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(shell mkdir .dep 2>/dev/null) $(wildcard .dep/*)

.PHONY: clean all

# *** EOF ***
